# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Tell Travis CI which distro to use
dist: trusty

# Setup a global environemnt and overide as needed
env:
  global:
    - WP_TRAVISCI=phpunit

cache:
  directories:
   - $HOME/.composer/cache/files
   - $HOME/.cache/yarn
   - $HOME/.phpbrew

branches:
  only:
  - master

# Next we define our matrix of additional build configurations to test against.
matrix:
  include:
  # Uncomment this once there are JavaScript tests.
  # - env: WP_TRAVISCI="npm test"
  - php: "7.1"
    env: SWITCH_TO_PHP=5.2 WP_VERSION=latest
  - php: "5.6"
    env: WP_VERSION=latest
  - php: "5.6"
    env: WP_VERSION=master
  - php: "5.6"
    env: WP_VERSION=previous
  - php: "7.0"
    env: WP_VERSION=latest
  - php: "7.1"
    env: WP_VERSION=latest
  - php: "7.2"
    env: WP_VERSION=latest

# Clones WordPress and configures our testing environment.
before_script:
    - phpenv config-rm xdebug.ini
    - export PLUGIN_BASE_DIR=$(basename $(pwd))
    - export PLUGIN_SLUG=$(basename $(pwd) | tr '[:upper:]' '[:lower:]')
    - source ~/.nvm/nvm.sh
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - |
        set -e
        source ./tests/bin/install-php-phpunit.sh
        set +e
    - nvm install 8
    - nvm use 8
    - ./tests/bin/prepare-wordpress.sh
    - mysql -e "set global wait_timeout = 3600;"

script:
    - echo "Running with the following versions:"
    - which php
    - php -v
    - which phpunit
    - phpunit --version
    - echo "Starting tests:"
    - ./tests/bin/run-travis.sh

sudo: false
